require 'test_helper'

class MatTest < ActiveSupport::TestCase
  test "An unique ID is autogenerated" do
    m = Mat.new
    m.save
    assert(m.valid?)
    assert(m.unique_hash != nil && m.unique_hash != "")
  end
end
